// ============================================
// StreamZ - Database Seed Script
// ============================================

import sql from './index.js';

async function seed() {
  console.log('🌱 Seeding database...');

  try {
    // ---- Insert sample stream ----
    const [stream] = await sql`
      INSERT INTO streams (platform, platform_stream_id, title, game_category, started_at, ended_at, status)
      VALUES (
        'twitch',
        'twitch_stream_001',
        'Epic Gaming Session - Let''s Go!',
        'Fortnite',
        NOW() - INTERVAL '2 hours',
        NOW() - INTERVAL '30 minutes',
        'captured'
      )
      ON CONFLICT (platform, platform_stream_id) DO NOTHING
      RETURNING *
    `;

    if (!stream) {
      console.log('⚠️  Sample stream already exists, skipping seed.');
      return;
    }

    console.log(`✅ Created sample stream: ${stream.id}`);

    // ---- Insert sample highlights ----
    const highlights = await sql`
      INSERT INTO highlights (stream_id, start_time, end_time, highlight_score, chat_spike_intensity, audio_energy_score, clip_duration, clip_type, status)
      VALUES
        (${stream.id}, 300, 420, 0.92, 8.5, 0.85, 120, 'medium', 'detected'),
        (${stream.id}, 1800, 1830, 0.78, 5.2, 0.72, 30, 'short', 'detected'),
        (${stream.id}, 5400, 6000, 0.88, 7.8, 0.80, 600, 'full', 'detected')
      RETURNING *
    `;

    console.log(`✅ Created ${highlights.length} sample highlights`);

    // ---- Insert sample AI content ----
    for (const highlight of highlights) {
      const [content] = await sql`
        INSERT INTO ai_content (highlight_id, target_platform, title, description, tags, hashtags, prompt_version, original_content)
        VALUES (
          ${highlight.id},
          'youtube_shorts',
          ${`INSANE ${highlight.clip_type.toUpperCase()} CLIP - You Won't Believe This! 🎮`},
          ${`An incredible ${highlight.clip_type} moment from our latest stream. Watch the chat go absolutely wild during this play! #gaming #twitch`},
          ARRAY['gaming', 'highlights', 'clip', ${highlight.clip_type}],
          ARRAY['#gaming', '#twitch', '#highlights', '#clip'],
          '1.0.0',
          ${sql.json({ rawTitle: 'Generated by AI v1.0.0' })}
        )
        RETURNING *
      `;

      console.log(`✅ Created AI content for highlight ${highlight.id}: ${content.id}`);

      // ---- Insert sample publish job ----
      const [job] = await sql`
        INSERT INTO publish_queue (ai_content_id, platform, scheduled_at, status)
        VALUES (
          ${content.id},
          'youtube_shorts',
          NOW() + INTERVAL '1 hour',
          'queued'
        )
        RETURNING *
      `;

      console.log(`✅ Created publish job: ${job.id}`);
    }

    // ---- Insert sample analytics ----
    const publishJobs = await sql`
      SELECT id, platform FROM publish_queue LIMIT 1
    `;

    if (publishJobs.length > 0) {
      await sql`
        INSERT INTO analytics (publish_queue_id, platform, views, likes, comments, shares, click_through_rate, average_watch_time, audience_retention_percent)
        VALUES (
          ${publishJobs[0].id},
          'youtube_shorts',
          15000,
          1200,
          89,
          234,
          0.08,
          25.5,
          65.2
        )
      `;
      console.log('✅ Created sample analytics record');
    }

    console.log('\n🎉 Seed complete!');
  } catch (error) {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  } finally {
    await sql.end();
  }
}

seed();
